# Server
server:
  port: 8080
  error:
    whitelabel.enabled: false
    include-exception: true
    include-message: on_param
    include-stacktrace: on_param
    include-binding-errors: on_param
# Spring
spring:
  profiles.active: local
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
  messages:
    basename: messages,errors
    encoding: utf-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: web
    password: web
    hikari:
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
# MyBatis
mybatis:
  type-aliases-package: io.ahakim.board.domain
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true







